# Generated by Django 4.1.2 on 2022-10-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='repetitions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
