# Generated by Django 4.1.2 on 2022-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_exercise_title_alter_trainingrecord_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
