# Generated by Django 4.1.2 on 2022-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_trainingrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='id',
            field=models.AutoField(db_column='tr_id', primary_key=True, serialize=False),
        ),
    ]
