# Generated by Django 4.1.2 on 2022-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_trainingrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
